# Generated by Django 3.0 on 2020-06-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20200627_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
