# Generated by Django 3.0 on 2020-06-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_auto_20200628_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
