# Generated by Django 3.0 on 2020-07-12 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0006_auto_20200628_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Custom', 'Custom')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Marital_Status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('In Relationship', 'In Relationship'), ('Divorced', 'Divorced')], max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendstatus', models.BooleanField()),
                ('frienduser1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1', to=settings.AUTH_USER_MODEL)),
                ('frienduser2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
