# Generated by Django 3.0 on 2020-07-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_auto_20200712_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='is_request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
