# Generated by Django 3.0 on 2020-08-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_name', models.CharField(max_length=200)),
                ('Expense_description', models.TextField(blank=True, null=True)),
                ('Amount', models.PositiveIntegerField()),
                ('Expense_date', models.DateField()),
                ('Expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_app.expense_cat')),
            ],
        ),
    ]
