# Generated by Django 3.0 on 2020-06-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200629_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='Upload_Image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Video',
            new_name='Upload_Video',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='Upoad_file',
        ),
    ]
