# Generated by Django 3.0 on 2020-06-30 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200629_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
