# Generated by Django 3.0 on 2020-07-05 10:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_commentlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentLike',
            new_name='PostLike',
        ),
    ]
